language: node_js
node_js:
- 12

services:
- docker

install:
- echo "nothing needs to be installed"

before_script:
- echo "no tests"

script:
- docker --version # print the version for logging
- docker-compose -f docker-compose-build.yaml build --parallel
- docker tag udagram-api-feed rahalh/udagram-api-feed:latest
- docker tag udagram-api-user rahalh/udagram-api-user:latest
- docker tag udagram-reverseproxy rahalh/udagram-reverseproxy:latest
- docker tag udagram-frontend rahalh/udagram-frontend:latest

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push rahalh/udagram-api-feed
- docker push rahalh/udagram-api-user
- docker push rahalh/udagram-reverseproxy
- docker push rahalh/udagram-frontend