apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    app: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: rahalh/udagram-reverseproxy
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "1000m"
          ports:
            - containerPort: 8080
      restartPolicy: Always 